export interface NanikiruPolicy {
  shantenWeight: number;
  ukeireWeight: number;
  goodShapeWeight: number;
  shapeWeight: number;
  routeWeight: number;
  valueWeight: number;
  defenseWeight: number;

  yakuhaiPairBonus: number;
  tanyaoLeanBonus: number;
  chiitoiPairThreshold: number;
  chiitoiBonus: number;
  honitsuSuitThreshold: number;
  honitsuBonus: number;
  ittsuBonus: number;
  sanshokuBonus: number;
  chantaBonus: number;
  toitoiBonus: number;
  doraBonus: number;
  akaDoraBonus: number;
  doraSideBonus: number;
  useTwoLayerValueForIishanten: boolean;
  twoLayerValueDivisor: number;
  twoLayerMinAveragePoints: number;
  twoLayerMaxDrawTypes: number;
  twoLayerMaxTenpaiDiscards: number;
  assumeRiichiForMenzenTwoLayer: boolean;
  secondaryValueRouteRatio: number;
  yakuhaiTanyaoConflictDecay: number;
  breakYakuhaiPairForTanyaoBonus: number;
  useScoringForTenpaiValue: boolean;
  scoringValueDivisor: number;
  routeCommitmentBonus: number;
  routeImprovementBonus: number;
  routeBreakPenalty: number;
  shantenBackUkeireMultiplier: number;
  shantenBackGoodShapeMultiplier: number;
  shantenBackDefenseOverrideDelta: number;
}

export const DEFAULT_NANIKIRU_POLICY: NanikiruPolicy = {
  shantenWeight: 1000,
  ukeireWeight: 10,
  goodShapeWeight: 8,
  shapeWeight: 1,
  routeWeight: 1,
  valueWeight: 1,
  defenseWeight: 1,

  yakuhaiPairBonus: 80,
  tanyaoLeanBonus: 60,
  chiitoiPairThreshold: 4,
  chiitoiBonus: 50,
  honitsuSuitThreshold: 8,
  honitsuBonus: 80,
  ittsuBonus: 65,
  sanshokuBonus: 60,
  chantaBonus: 45,
  toitoiBonus: 55,
  doraBonus: 90,
  akaDoraBonus: 70,
  doraSideBonus: 18,
  useTwoLayerValueForIishanten: true,
  twoLayerValueDivisor: 160,
  twoLayerMinAveragePoints: 1500,
  twoLayerMaxDrawTypes: 5,
  twoLayerMaxTenpaiDiscards: 2,
  assumeRiichiForMenzenTwoLayer: true,
  secondaryValueRouteRatio: 0.35,
  yakuhaiTanyaoConflictDecay: 0.6,
  breakYakuhaiPairForTanyaoBonus: 50,
  useScoringForTenpaiValue: true,
  scoringValueDivisor: 100,
  routeCommitmentBonus: 36,
  routeImprovementBonus: 55,
  routeBreakPenalty: 45,
  shantenBackUkeireMultiplier: 0.35,
  shantenBackGoodShapeMultiplier: 0.25,
  shantenBackDefenseOverrideDelta: 300,
};
